// Supported regional languages with native script & speech synthesis codes
export const LANGUAGES = [
  {
    code: 'hi',
    name: 'हिन्दी',
    englishName: 'Hindi',
    locale: 'hi-IN',
    greeting: 'नमस्ते! तंतु में आपका स्वागत है।',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'en',
    name: 'English',
    englishName: 'English',
    locale: 'en-IN',
    greeting: 'Welcome to TANTU Artisan App.',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'bn',
    name: 'বাংলা',
    englishName: 'Bengali',
    locale: 'bn-IN',
    greeting: 'নমস্কার! তন্তু-তে আপনাকে স্বাগতম।',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'as',
    name: 'অসমীয়া',
    englishName: 'Assamese',
    locale: 'as-IN',
    greeting: 'নমস্কাৰ! তন্তুলৈ আপোনাক স্বাগতম।',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'or',
    name: 'ଓଡ଼ିଆ',
    englishName: 'Odia',
    locale: 'or-IN',
    greeting: 'ନମସ୍କାର! ତନ୍ତୁ କୁ ସ୍ଵାଗତ।',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'mr',
    name: 'मराठी',
    englishName: 'Marathi',
    locale: 'mr-IN',
    greeting: 'नमस्कार! तंतू मध्ये आपले स्वागत आहे.',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'gu',
    name: 'ગુજરાતી',
    englishName: 'Gujarati',
    locale: 'gu-IN',
    greeting: 'નમસ્તે! તંતુ માં તમારું સ્વાગત છે.',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'te',
    name: 'తెలుగు',
    englishName: 'Telugu',
    locale: 'te-IN',
    greeting: 'నమస్కారం! తంతు కు స్వాగతం.',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'ta',
    name: 'தமிழ்',
    englishName: 'Tamil',
    locale: 'ta-IN',
    greeting: 'வணக்கம்! தந்து-விற்கு நல்வரவு.',
    greetingEn: 'Welcome to TANTU'
  }
];

// UI String dictionary for high accessibility
export const TRANSLATIONS = {
  hi: {
    appTitle: 'तंतु TANTU',
    tagline: 'कारीगरों के लिए स्मार्ट कैटलॉगिंग और बाज़ार मंच',
    artisanRole: 'कारीगर (Artisan)',
    buyerRole: 'खरीदार (Buyer)',
    selectLanguage: 'अपनी भाषा चुनें',
    selectLanguageSub: 'Select your preferred language to continue',
    continueBtn: 'आगे बढ़ें (Continue)',
    home: 'होम',
    addProduct: 'उत्पाद जोड़ें',
    myProducts: 'मेरे शिल्प',
    orders: 'ऑर्डर अनुरोध',
    marketplace: 'कारीगर बाज़ार',
    hello: 'नमस्ते',
    welcomeBack: 'आज आप किस शिल्प को बाज़ार में प्रस्तुत करेंगे?',
    addNewCraft: 'नया शिल्प कैटलॉग बनाएं',
    addNewCraftSub: 'फोटो खींचें और अपनी आवाज़ में बताएं — AI अपने आप विवरण और कीमत तय करेगा।',
    startNow: 'शुरू करें (Start)',
    totalProducts: 'कुल शिल्प',
    activeOrders: 'सक्रिय ऑर्डर',
    estEarnings: 'अनुमानित आय',
    recentUploads: 'हाल ही में जोड़े गए शिल्प',
    viewAll: 'सभी देखें',
    step1Photo: '1. फोटो खींचें या चुनें',
    step1PhotoSub: 'शिल्प का साफ फोटो लें',
    step2Voice: '2. बोलकर बताएं',
    step2VoiceSub: 'माइक दबाकर 30 सेकंड में उत्पाद के बारे में बताएं',
    step3Ai: '3. AI प्रसंस्करण',
    step3AiSub: 'तंतु AI स्मार्ट कैटलॉग तैयार कर रहा है',
    step4Catalog: '4. स्मार्ट कैटलॉग',
    step4CatalogSub: 'तैयार कैटलॉग जांचें और प्रकाशित करें',
    takePhoto: 'कैमरा खोलें',
    uploadPhoto: 'गैलरी से चुनें',
    orUseSample: 'या डेमो के लिए तैयार शिल्प चुनें:',
    tapToRecord: 'बोलने के लिए माइक दबाएं',
    listening: 'हम सुन रहे हैं... बोलिए',
    stopRecording: 'बोलना समाप्त करें',
    playVoice: 'आवाज़ दोबारा सुनें',
    reRecord: 'फिर से रिकॉर्ड करें',
    recordedSuccess: 'आपकी आवाज़ रिकॉर्ड हो गई है!',
    proceedToAi: 'AI कैटलॉग तैयार करें',
    approvePublish: 'स्वीकार करें और प्रकाशित करें',
    editDetails: 'विवरण में सुधार करें',
    publishedSuccess: 'बधाई! आपका शिल्प सफलतापूर्वक प्रकाशित हो गया है।',
    material: 'सामग्री (Material)',
    category: 'श्रेणी (Category)',
    dimensions: 'माप/आकार (Dimensions)',
    productionTime: 'बनाने में लगा समय (Time)',
    tags: 'टैग्स (Tags)',
    heritageStory: 'शिल्पकार की कहानी व विरासत',
    sentiment: 'संवेदना और शैली',
    suggestedPrice: 'AI अनुमानित उचित मूल्य',
    bulkOrderAvailable: 'थोक खरीद उपलब्ध',
    buyerInquiry: 'खरीदार ऑर्डर अनुरोध',
    requestUnits: 'थोक ऑर्डर अनुरोध भेजें',
    quantity: 'मात्रा (Units)',
    buyerName: 'आपका नाम / संस्था',
    buyerContact: 'फोन नंबर / ईमेल',
    offeredPrice: 'प्रस्तावित दर प्रति इकाई (₹)',
    sendRequest: 'अनुरोध भेजें (Send Request)',
    orderSubmitted: 'ऑर्डर अनुरोध भेजा गया!',
    pending: 'लंबित (Pending)',
    accepted: 'स्वीकृत (Accepted)',
    listenToScreen: 'इस पृष्ठ को सुनें',
    viewEnhanced: 'AI स्टूडियो लाइटिंग फोटो',
    viewOriginal: 'मूल फोटो',
    aiConfidence: 'AI सटीकता'
  },
  en: {
    appTitle: 'TANTU तंतु',
    tagline: 'AI Market Linkage & Smart Cataloging for Marginalized Artisans',
    artisanRole: 'Artisan View',
    buyerRole: 'Buyer View',
    selectLanguage: 'Choose Your Language',
    selectLanguageSub: 'अपनी पसंदीदा भाषा चुनें',
    continueBtn: 'Continue',
    home: 'Home',
    addProduct: 'Add Craft',
    myProducts: 'My Crafts',
    orders: 'Orders',
    marketplace: 'Marketplace',
    hello: 'Hello',
    welcomeBack: 'What handcrafted creation would you like to catalog today?',
    addNewCraft: 'Create Smart AI Catalogue',
    addNewCraftSub: 'Take a photo & describe it in your native voice. AI writes the story & calculates fair pricing.',
    startNow: 'Start Cataloging',
    totalProducts: 'Listed Crafts',
    activeOrders: 'Order Requests',
    estEarnings: 'Est. Earnings',
    recentUploads: 'Recent Catalog Listings',
    viewAll: 'View All',
    step1Photo: '1. Photo Capture',
    step1PhotoSub: 'Capture or pick a clear craft photo',
    step2Voice: '2. Voice Narrative',
    step2VoiceSub: 'Tap mic and describe your craft in your native language',
    step3Ai: '3. AI Synthesis',
    step3AiSub: 'TANTU AI is generating the bilingual catalogue',
    step4Catalog: '4. Smart Catalogue',
    step4CatalogSub: 'Review generated catalogue & publish',
    takePhoto: 'Open Camera',
    uploadPhoto: 'Upload from Gallery',
    orUseSample: 'Or tap a demo artisan craft:',
    tapToRecord: 'Tap Mic to Speak',
    listening: 'Listening to your voice... Speak now',
    stopRecording: 'Finish Speaking',
    playVoice: 'Playback Audio',
    reRecord: 'Record Again',
    recordedSuccess: 'Voice note recorded successfully!',
    proceedToAi: 'Generate AI Catalogue',
    approvePublish: 'Approve & Publish to Marketplace',
    editDetails: 'Edit Catalogue',
    publishedSuccess: 'Congratulations! Your handcrafted product is now live in the buyer marketplace.',
    material: 'Material',
    category: 'Craft Category',
    dimensions: 'Dimensions',
    productionTime: 'Production Time',
    tags: 'Tags',
    heritageStory: 'Artisan Heritage & Narrative',
    sentiment: 'Sentiment & Tone',
    suggestedPrice: 'AI Suggested Fair Market Price',
    bulkOrderAvailable: 'Bulk B2B Available',
    buyerInquiry: 'Buyer Inquiries',
    requestUnits: 'Request Bulk Order',
    quantity: 'Quantity (Units)',
    buyerName: 'Buyer / Organization Name',
    buyerContact: 'Phone / Email Contact',
    offeredPrice: 'Offered Price per Unit (₹)',
    sendRequest: 'Submit Order Request',
    orderSubmitted: 'Order Request Submitted!',
    pending: 'Pending Review',
    accepted: 'Accepted',
    listenToScreen: 'Read page aloud',
    viewEnhanced: 'AI Studio Lighting',
    viewOriginal: 'Raw Capture',
    aiConfidence: 'AI Confidence'
  }
};

export const getTranslation = (lang, key) => {
  const dictionary = TRANSLATIONS[lang] || TRANSLATIONS['hi'];
  return dictionary[key] || TRANSLATIONS['en'][key] || key;
};
