// Supported regional languages with native script & speech synthesis codes
// Contains ONLY the 7 verified functional languages for TANTU/ShilpVani
export const LANGUAGES = [
  {
    code: 'en',
    name: 'English',
    englishName: 'English',
    locale: 'en-IN',
    greeting: 'Welcome to TANTU Artisan App.',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'hi',
    name: 'हिन्दी',
    englishName: 'Hindi',
    locale: 'hi-IN',
    greeting: 'नमस्ते! तंतु में आपका स्वागत है।',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'bn',
    name: 'বাংলা',
    englishName: 'Bengali',
    locale: 'bn-IN',
    greeting: 'নমস্কার! তন্তু-তে আপনাকে স্বাগতম।',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'mr',
    name: 'मराठी',
    englishName: 'Marathi',
    locale: 'mr-IN',
    greeting: 'नमस्कार! तंतू मध्ये आपले स्वागत आहे.',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'as',
    name: 'অসমীয়া',
    englishName: 'Assamese',
    locale: 'as-IN',
    greeting: 'নমস্কাৰ! তন্তুলৈ আপোনাক স্বাগতম।',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'ta',
    name: 'தமிழ்',
    englishName: 'Tamil',
    locale: 'ta-IN',
    greeting: 'வணக்கம்! தந்து-விற்கு நல்வரவு.',
    greetingEn: 'Welcome to TANTU'
  },
  {
    code: 'te',
    name: 'తెలుగు',
    englishName: 'Telugu',
    locale: 'te-IN',
    greeting: 'నమస్కారం! తంతు కు స్వాగతం.',
    greetingEn: 'Welcome to TANTU'
  }
];

// UI String dictionary for high accessibility across all 7 supported languages
export const TRANSLATIONS = {
  hi: {
    appTitle: 'तंतु TANTU',
    tagline: 'कारीगरों के लिए स्मार्ट कैटलॉगिंग और बाज़ार मंच',
    artisanRole: 'कारीगर (Artisan)',
    buyerRole: 'खरीदार (Buyer)',
    selectLanguage: 'अपनी भाषा चुनें',
    selectLanguageSub: 'Select your preferred language to continue',
    continueBtn: 'आगे बढ़ें (Continue)',
    home: 'होम',
    addProduct: 'उत्पाद जोड़ें',
    myProducts: 'मेरे शिल्प',
    orders: 'ऑर्डर अनुरोध',
    marketplace: 'कारीगर बाज़ार',
    hello: 'नमस्ते',
    welcomeBack: 'आज आप किस शिल्प को बाज़ार में प्रस्तुत करेंगे?',
    addNewCraft: 'नया शिल्प कैटलॉग बनाएं',
    addNewCraftSub: 'फोटो खींचें और अपनी आवाज़ में बताएं — AI अपने आप विवरण और कीमत तय करेगा।',
    startNow: 'शुरू करें (Start)',
    totalProducts: 'कुल शिल्प',
    activeOrders: 'सक्रिय ऑर्डर',
    estEarnings: 'अनुमानित आय',
    recentUploads: 'हाल ही में जोड़े गए शिल्प',
    viewAll: 'सभी देखें',
    step1Photo: '1. फोटो खींचें या चुनें',
    step1PhotoSub: 'शिल्प का साफ फोटो लें',
    step2Voice: '2. बोलकर बताएं',
    step2VoiceSub: 'माइक दबाकर 30 सेकंड में उत्पाद के बारे में बताएं',
    step3Ai: '3. AI प्रसंस्करण',
    step3AiSub: 'तंतु AI स्मार्ट कैटलॉग तैयार कर रहा है',
    step4Catalog: '4. स्मार्ट कैटलॉग',
    step4CatalogSub: 'तैयार कैटलॉग जांचें और प्रकाशित करें',
    takePhoto: 'कैमरा खोलें',
    uploadPhoto: 'गैलरी से चुनें',
    orUseSample: 'या डेमो के लिए तैयार शिल्प चुनें:',
    tapToRecord: 'बोलने के लिए माइक दबाएं',
    listening: 'हम सुन रहे हैं... बोलिए',
    stopRecording: 'बोलना समाप्त करें',
    playVoice: 'आवाज़ दोबारा सुनें',
    reRecord: 'फिर से रिकॉर्ड करें',
    recordedSuccess: 'आपकी आवाज़ रिकॉर्ड हो गई है!',
    proceedToAi: 'AI कैटलॉग तैयार करें',
    approvePublish: 'स्वीकार करें और प्रकाशित करें',
    editDetails: 'विवरण में सुधार करें',
    publishedSuccess: 'बधाई! आपका शिल्प सफलतापूर्वक प्रकाशित हो गया है।',
    material: 'सामग्री (Material)',
    category: 'श्रेणी (Category)',
    dimensions: 'माप/आकार (Dimensions)',
    productionTime: 'बनाने में लगा समय (Time)',
    tags: 'टैग्स (Tags)',
    heritageStory: 'शिल्पकार की कहानी व विरासत',
    sentiment: 'संवेदना और शैली',
    suggestedPrice: 'AI अनुमानित उचित मूल्य',
    bulkOrderAvailable: 'थोक खरीद उपलब्ध',
    buyerInquiry: 'खरीदार ऑर्डर अनुरोध',
    requestUnits: 'थोक ऑर्डर अनुरोध भेजें',
    quantity: 'मात्रा (Units)',
    buyerName: 'आपका नाम / संस्था',
    buyerContact: 'फोन नंबर / ईमेल',
    offeredPrice: 'प्रस्तावित दर प्रति इकाई (₹)',
    sendRequest: 'अनुरोध भेजें (Send Request)',
    orderSubmitted: 'ऑर्डर अनुरोध भेजा गया!',
    pending: 'लंबित (Pending)',
    accepted: 'स्वीकृत (Accepted)',
    listenToScreen: 'इस पृष्ठ को सुनें',
    viewEnhanced: 'AI स्टूडियो लाइटिंग फोटो',
    viewOriginal: 'मूल फोटो',
    aiConfidence: 'AI सटीकता'
  },
  en: {
    appTitle: 'TANTU तंतु',
    tagline: 'AI Market Linkage & Smart Cataloging for Marginalized Artisans',
    artisanRole: 'Artisan View',
    buyerRole: 'Buyer View',
    selectLanguage: 'Choose Your Language',
    selectLanguageSub: 'अपनी पसंदीदा भाषा चुनें',
    continueBtn: 'Continue',
    home: 'Home',
    addProduct: 'Add Craft',
    myProducts: 'My Crafts',
    orders: 'Orders',
    marketplace: 'Marketplace',
    hello: 'Hello',
    welcomeBack: 'What handcrafted creation would you like to catalog today?',
    addNewCraft: 'Create Smart AI Catalogue',
    addNewCraftSub: 'Take a photo & describe it in your native voice. AI writes the story & calculates fair pricing.',
    startNow: 'Start Cataloging',
    totalProducts: 'Listed Crafts',
    activeOrders: 'Order Requests',
    estEarnings: 'Est. Earnings',
    recentUploads: 'Recent Catalog Listings',
    viewAll: 'View All',
    step1Photo: '1. Photo Capture',
    step1PhotoSub: 'Capture or pick a clear craft photo',
    step2Voice: '2. Voice Narrative',
    step2VoiceSub: 'Tap mic and describe your craft in your native language',
    step3Ai: '3. AI Synthesis',
    step3AiSub: 'TANTU AI is generating the bilingual catalogue',
    step4Catalog: '4. Smart Catalogue',
    step4CatalogSub: 'Review generated catalogue & publish',
    takePhoto: 'Open Camera',
    uploadPhoto: 'Upload from Gallery',
    orUseSample: 'Or tap a demo artisan craft:',
    tapToRecord: 'Tap Mic to Speak',
    listening: 'Listening to your voice... Speak now',
    stopRecording: 'Finish Speaking',
    playVoice: 'Playback Audio',
    reRecord: 'Record Again',
    recordedSuccess: 'Voice note recorded successfully!',
    proceedToAi: 'Generate AI Catalogue',
    approvePublish: 'Approve & Publish to Marketplace',
    editDetails: 'Edit Catalogue',
    publishedSuccess: 'Congratulations! Your handcrafted product is now live in the buyer marketplace.',
    material: 'Material',
    category: 'Craft Category',
    dimensions: 'Dimensions',
    productionTime: 'Production Time',
    tags: 'Tags',
    heritageStory: 'Artisan Heritage & Narrative',
    sentiment: 'Sentiment & Tone',
    suggestedPrice: 'AI Suggested Fair Market Price',
    bulkOrderAvailable: 'Bulk B2B Available',
    buyerInquiry: 'Buyer Inquiries',
    requestUnits: 'Request Bulk Order',
    quantity: 'Quantity (Units)',
    buyerName: 'Buyer / Organization Name',
    buyerContact: 'Phone / Email Contact',
    offeredPrice: 'Offered Price per Unit (₹)',
    sendRequest: 'Submit Order Request',
    orderSubmitted: 'Order Request Submitted!',
    pending: 'Pending Review',
    accepted: 'Accepted',
    listenToScreen: 'Read page aloud',
    viewEnhanced: 'AI Studio Lighting',
    viewOriginal: 'Raw Capture',
    aiConfidence: 'AI Confidence'
  },
  bn: {
    appTitle: 'তন্তু TANTU',
    tagline: 'কারিগরদের জন্য স্মার্ট ক্যাটালগিং ও বাজার সংযোগ',
    artisanRole: 'কারিগর (Artisan)',
    buyerRole: 'ক্রেতা (Buyer)',
    selectLanguage: 'আপনার ভাষা বেছে নিন',
    selectLanguageSub: 'Select your preferred language to continue',
    continueBtn: 'এগিয়ে যান (Continue)',
    home: 'হোম',
    addProduct: 'পণ্য যোগ করুন',
    myProducts: 'আমার শিল্পকর্ম',
    orders: 'অর্ডার অনুরোধ',
    marketplace: 'কারিগর বাজার',
    hello: 'নমস্কার',
    welcomeBack: 'আজ আপনি কোন শিল্পকর্মটি বাজারে প্রদর্শন করবেন?',
    addNewCraft: 'নতুন স্মার্ট ক্যাটালগ তৈরি করুন',
    addNewCraftSub: 'ছবি তুলুন এবং নিজের ভাষায় বলুন — AI স্বয়ক্রিয়ভাবে বিবরণ ও ন্যায্য মূল্য নির্ধারণ করবে।',
    startNow: 'শুরু করুন (Start)',
    totalProducts: 'মোট শিল্পকর্ম',
    activeOrders: 'সক্রিয় অর্ডার',
    estEarnings: 'আনুমানিক আয়',
    recentUploads: 'সম্প্রতি যুক্ত শিল্পকর্ম',
    viewAll: 'সব দেখুন',
    step1Photo: '১. ছবি তুলুন বা বেছে নিন',
    step1PhotoSub: 'শিল্পকর্মের পরিষ্কার ছবি তুলুন',
    step2Voice: '২. মুখে বলে জানান',
    step2VoiceSub: 'মাইক চেপে ৩০ সেকেন্ডে পণ্যটি সম্পর্কে বলুন',
    step3Ai: '৩. AI প্রক্রিয়াকরণ',
    step3AiSub: 'তন্তু AI স্মার্ট ক্যাটালগ প্রস্তুত করছে',
    step4Catalog: '৪. স্মার্ট ক্যাটালগ',
    step4CatalogSub: 'প্রস্তুত ক্যাটালগ যাচাই করুন ও প্রকাশ করুন',
    takePhoto: 'ক্যামেরা খুলুন',
    uploadPhoto: 'গ্যালারি থেকে বেছে নিন',
    orUseSample: 'বা ডেমোর জন্য তৈরি নমুনা বাছুন:',
    tapToRecord: 'বলার জন্য মাইক চাপুন',
    listening: 'শুনছি... বলুন',
    stopRecording: 'বলা শেষ করুন',
    playVoice: 'রেকর্ডিং শুনুন',
    reRecord: 'আবার রেকর্ড করুন',
    recordedSuccess: 'আপনার কণ্ঠ সফলভাবে রেকর্ড হয়েছে!',
    proceedToAi: 'AI ক্যাটালগ তৈরি করুন',
    approvePublish: 'অনুমোদন ও প্রকাশ করুন',
    editDetails: 'বিবরণ সংশোধন করুন',
    publishedSuccess: 'অভিনন্দন! আপনার শিল্পকর্ম সফলভাবে বাজারে প্রকাশিত হয়েছে।',
    material: 'উপাদান (Material)',
    category: 'বিভাগ (Category)',
    dimensions: 'পরিমাপ/আকার (Dimensions)',
    productionTime: 'তৈরির সময় (Time)',
    tags: 'ট্যাগ (Tags)',
    heritageStory: 'কারিগরদের ঐতিহ্য ও গল্প',
    sentiment: 'অনুভূতি ও শিল্পশৈলী',
    suggestedPrice: 'AI নির্ধারিত ন্যায্য মূল্য',
    bulkOrderAvailable: 'পাইকারি ক্রয় উপলব্ধ',
    buyerInquiry: 'ক্রেতার অর্ডার অনুরোধ',
    requestUnits: 'পাইকারি অর্ডার অনুরোধ পাঠান',
    quantity: 'পরিমাণ (Units)',
    buyerName: 'আপনার নাম / সংস্থা',
    buyerContact: 'ফোন নম্বর / ইমেইল',
    offeredPrice: 'প্রস্তাবিত দর প্রতি একক (₹)',
    sendRequest: 'অনুরোধ পাঠান (Send Request)',
    orderSubmitted: 'অর্ডার অনুরোধ পাঠানো হয়েছে!',
    pending: 'অপেক্ষারত (Pending)',
    accepted: 'গৃহীত (Accepted)',
    listenToScreen: 'এই পাতাটি শুনুন',
    viewEnhanced: 'AI স্টুডিও ফটো',
    viewOriginal: 'মূল ছবি',
    aiConfidence: 'AI নির্ভুলতা'
  },
  mr: {
    appTitle: 'तंतू TANTU',
    tagline: 'कारागिरांसाठी स्मार्ट कॅटलॉगिंग आणि बाजारपेठ मंच',
    artisanRole: 'कारागीर (Artisan)',
    buyerRole: 'खरेदीदार (Buyer)',
    selectLanguage: 'तुमची भाषा निवडा',
    selectLanguageSub: 'Select your preferred language to continue',
    continueBtn: 'पुढे जा (Continue)',
    home: 'होम',
    addProduct: 'उत्पादन जोडा',
    myProducts: 'माझी शिल्पे',
    orders: 'ऑर्डर विनंत्या',
    marketplace: 'कारागीर बाजार',
    hello: 'नमस्कार',
    welcomeBack: 'आज तुम्ही कोणती हस्तकला सादर करणार आहात?',
    addNewCraft: 'नवीन स्मार्ट कॅटलॉग तयार करा',
    addNewCraftSub: 'फोटो काढा आणि आपल्या भाषेत सांगा — AI आपोआप वर्णन आणि किंमत ठरवेल.',
    startNow: 'सुरू करा (Start)',
    totalProducts: 'एकूण शिल्पे',
    activeOrders: 'सक्रिय ऑर्डर्स',
    estEarnings: 'अंदाजे उत्पन्न',
    recentUploads: 'नुकतीच जोडलेली शिल्पे',
    viewAll: 'सर्व पहा',
    step1Photo: '१. फोटो काढा किंवा निवडा',
    step1PhotoSub: 'शिल्पाचा स्पष्ट फोटो घ्या',
    step2Voice: '२. बोलून सांगा',
    step2VoiceSub: 'माइक दाबून ३० सेकंदात उत्पादनाबद्दल सांगा',
    step3Ai: '३. AI प्रक्रिया',
    step3AiSub: 'तंतू AI स्मार्ट कॅटलॉग तयार करत आहे',
    step4Catalog: '४. स्मार्ट कॅटलॉग',
    step4CatalogSub: 'तयार कॅटलॉग तपासा आणि प्रकाशित करा',
    takePhoto: 'कॅमेरा उघडा',
    uploadPhoto: 'गॅलरीतून निवडा',
    orUseSample: 'किंवा डेमोसाठी तयार शिल्प निवडा:',
    tapToRecord: 'बोलण्यासाठी माइक दाबा',
    listening: 'ऐकत आहोत... बोला',
    stopRecording: 'बोलणे पूर्ण करा',
    playVoice: 'आवाज पुन्हा ऐका',
    reRecord: 'पुन्हा रेकॉर्ड करा',
    recordedSuccess: 'तुमचा आवाज रेकॉर्ड झाला आहे!',
    proceedToAi: 'AI कॅटलॉग तयार करा',
    approvePublish: 'मंजूर करा आणि प्रकाशित करा',
    editDetails: 'तपशील बदला',
    publishedSuccess: 'अभिनंदन! तुमचे उत्पादन यशस्वीरीत्या बाजारात प्रकाशित झाले आहे.',
    material: 'साहित्य (Material)',
    category: 'श्रेणी (Category)',
    dimensions: 'आकार/मापे (Dimensions)',
    productionTime: 'निर्मिती वेळ (Time)',
    tags: 'टॅग्ज (Tags)',
    heritageStory: 'कारागिराची कथा व परंपरा',
    sentiment: 'भावना आणि शैली',
    suggestedPrice: 'AI अंदाजित रास्त किंमत',
    bulkOrderAvailable: 'घाऊक खरेदी उपलब्ध',
    buyerInquiry: 'खरेदीदार ऑर्डर विनंती',
    requestUnits: 'घाऊक ऑर्डर विनंती पाठवा',
    quantity: 'प्रमाण (Units)',
    buyerName: 'तुमचे नाव / संस्था',
    buyerContact: 'फोन नंबर / ईमेल',
    offeredPrice: 'प्रस्तावित दर प्रति नग (₹)',
    sendRequest: 'विनंती पाठवा (Send Request)',
    orderSubmitted: 'ऑर्डर विनंती पाठवली गेली!',
    pending: 'प्रलंबित (Pending)',
    accepted: 'स्वीकृत (Accepted)',
    listenToScreen: 'हे पान ऐका',
    viewEnhanced: 'AI स्टुडिओ फोटो',
    viewOriginal: 'मूळ फोटो',
    aiConfidence: 'AI अचूकता'
  },
  as: {
    appTitle: 'তন্তু TANTU',
    tagline: 'শিল্পীসকলৰ বাবে স্মাৰ্ট কেটেলগ আৰু বজাৰ সংযোগ',
    artisanRole: 'শিল্পী (Artisan)',
    buyerRole: 'গ্ৰাহক (Buyer)',
    selectLanguage: 'আপোনাৰ ভাষা বাছক',
    selectLanguageSub: 'Select your preferred language to continue',
    continueBtn: 'আগবাঢ়ক (Continue)',
    home: 'হোম',
    addProduct: 'সামগ্ৰী যোগ কৰক',
    myProducts: 'মোৰ শিল্পকলা',
    orders: 'অৰ্ডাৰ অনুৰোধ',
    marketplace: 'শিল্পী বজাৰ',
    hello: 'নমস্কাৰ',
    welcomeBack: 'আজি আপুনি কোনটো শিল্পকলা প্ৰদৰ্শন কৰিব?',
    addNewCraft: 'নতুন স্মাৰ্ট কেটেলগ বনাওক',
    addNewCraftSub: 'ফটো তোলক আৰু নিজৰ মাতত কওক — AI য়ে নিজে নিজে বিৱৰণ আৰু ন্যায্য মূল্য নিৰ্ধাৰণ কৰিব।',
    startNow: 'আৰম্ভ কৰক (Start)',
    totalProducts: 'মুঠ শিল্পকলা',
    activeOrders: 'সক্ৰিয় অৰ্ডাৰ',
    estEarnings: 'আনুমানিক উপাৰ্জন',
    recentUploads: 'শেহতীয়াকৈ যোগ কৰা শিল্পকলা',
    viewAll: 'সকলো চাওক',
    step1Photo: '১. ফটো তোলক বা বাছক',
    step1PhotoSub: 'শিল্পকলাৰ স্পষ্ট ফটো লওক',
    step2Voice: '২. মাত দি কওক',
    step2VoiceSub: 'মাইক টিপি ৩০ ছেকেণ্ডত সামগ্ৰীৰ বিষয়ে কওক',
    step3Ai: '৩. AI প্ৰক্ৰিয়াকৰণ',
    step3AiSub: 'তন্তু AI য়ে স্মাৰ্ট কেটেলগ প্ৰস্তুত কৰিছে',
    step4Catalog: '৪. স্মাৰ্ট কেটেলগ',
    step4CatalogSub: 'প্ৰস্তুত কেটেলগ পৰীক্ষা কৰি প্ৰকাশ কৰক',
    takePhoto: 'কেমেৰা খোলক',
    uploadPhoto: 'গেলেৰীৰ পৰা বাছক',
    orUseSample: 'বা নমুনা শিল্পকলা বাছক:',
    tapToRecord: 'ক’বলৈ মাইক টিপক',
    listening: 'শুনি আছোঁ... কওক',
    stopRecording: 'কোৱা সমাপ্ত কৰক',
    playVoice: 'ৰেকৰ্ডিং শুনক',
    reRecord: 'পুনৰ ৰেকৰ্ড কৰক',
    recordedSuccess: 'আপোনাৰ কণ্ঠ ৰেকৰ্ড হ’ল!',
    proceedToAi: 'AI কেটেলগ প্ৰস্তুত কৰক',
    approvePublish: 'অনুমোদন আৰু প্ৰকাশ কৰক',
    editDetails: 'বিৱৰণ শুধৰাওক',
    publishedSuccess: 'অভিনন্দন! আপোনাৰ শিল্পকলা সফলভাৱে বজাৰত প্ৰকাশিত হ’ল।',
    material: 'সামগ্ৰী (Material)',
    category: 'শ্ৰেণী (Category)',
    dimensions: 'জোখ/আকাৰ (Dimensions)',
    productionTime: 'নিৰ্মাণৰ সময় (Time)',
    tags: 'টেগ (Tags)',
    heritageStory: 'শিল্পীৰ গল্প আৰু ঐতিহ্য',
    sentiment: 'ভাৱ আৰু শৈলী',
    suggestedPrice: 'AI আনুমানিক ন্যায্য মূল্য',
    bulkOrderAvailable: 'পাইকাৰী ক্ৰয় উপলব্ধ',
    buyerInquiry: 'গ্ৰাহকৰ অৰ্ডাৰ অনুৰোধ',
    requestUnits: 'পাইকাৰী অৰ্ডাৰ অনুৰোধ পঠিয়াওক',
    quantity: 'পৰিমাণ (Units)',
    buyerName: 'আপোনাৰ নাম / প্ৰতিষ্ঠান',
    buyerContact: 'ফোন নম্বৰ / ইমেইল',
    offeredPrice: 'প্ৰস্তাৱিত মূল্য প্ৰতি একক (₹)',
    sendRequest: 'অনুৰোধ পঠিয়াওক (Send Request)',
    orderSubmitted: 'অৰ্ডাৰ অনুৰোধ পঠিওৱা হ’ল!',
    pending: 'অপেক্ষাকৃত (Pending)',
    accepted: 'গৃহীত (Accepted)',
    listenToScreen: 'এই পৃষ্ঠাখন শুনক',
    viewEnhanced: 'AI ষ্টুডিঅ’ ফটো',
    viewOriginal: 'মূল ফটো',
    aiConfidence: 'AI নিৰ্ভুলতা'
  },
  ta: {
    appTitle: 'தந்து TANTU',
    tagline: 'கைவினைஞர்களுக்கான ஸ்மார்ட் பட்டியல் மற்றும் சந்தை இணைப்பு',
    artisanRole: 'கைவினைஞர் (Artisan)',
    buyerRole: 'வாங்குபவர் (Buyer)',
    selectLanguage: 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
    selectLanguageSub: 'Select your preferred language to continue',
    continueBtn: 'தொடரவும் (Continue)',
    home: 'முகப்பு',
    addProduct: 'கைவினைப் பொருள் சேர்க்க',
    myProducts: 'என் தயாரிப்புகள்',
    orders: 'ஆர்டர் கோரிக்கைகள்',
    marketplace: 'கைவினைச் சந்தை',
    hello: 'வணக்கம்',
    welcomeBack: 'இன்று எந்த கைவினைப் பொருளைப் பட்டியலிட விரும்புகிறீர்கள்?',
    addNewCraft: 'புதிய AI பட்டியலை உருவாக்கவும்',
    addNewCraftSub: 'படம் எடுத்து உங்கள் குரலில் விவரிக்கவும் — AI தானாகவே விளக்கம் மற்றும் நியாய விலையை உருவாக்கும்.',
    startNow: 'தொடங்குங்கள் (Start)',
    totalProducts: 'மொத்த தயாரிப்புகள்',
    activeOrders: 'செயலில் உள்ள ஆர்டர்கள்',
    estEarnings: 'மதிப்பிடப்பட்ட வருமானம்',
    recentUploads: 'சமீபத்திய தயாரிப்புகள்',
    viewAll: 'அனைத்தும் பார்க்க',
    step1Photo: '1. புகைப்படம் எடுக்கவும் அல்லது தேர்ந்தெடுக்கவும்',
    step1PhotoSub: 'கைவினைப் பொருளின் தெளிவான படம் எடுக்கவும்',
    step2Voice: '2. குரல் மூலம் சொல்லுங்கள்',
    step2VoiceSub: 'மைக்கை அழுத்தி 30 வினாடிகளில் தயாரிப்பை விவரிக்கவும்',
    step3Ai: '3. AI செயலாக்கம்',
    step3AiSub: 'தந்து AI ஸ்மார்ட் பட்டியலைத் தயாரிக்கிறது',
    step4Catalog: '4. ஸ்மார்ட் பட்டியல்',
    step4CatalogSub: 'தயாரான பட்டியலைச் சரிபார்த்து வெளியிடவும்',
    takePhoto: 'கேமரா திறக்கவும்',
    uploadPhoto: 'கேலரியில் இருந்து தேர்வுசெய்க',
    orUseSample: 'அல்லது மாதிரிப் பொருளைத் தேர்ந்தெடுக்கவும்:',
    tapToRecord: 'பேச மைக்கை அழுத்தவும்',
    listening: 'கேட்கிறது... பேசுங்கள்',
    stopRecording: 'பேசி முடிக்கவும்',
    playVoice: 'குரலைக் கேட்கவும்',
    reRecord: 'மீண்டும் பதிவுசெய்க',
    recordedSuccess: 'உங்கள் குரல் வெற்றிகரமாகப் பதிவானது!',
    proceedToAi: 'AI பட்டியலை உருவாக்கவும்',
    approvePublish: 'ஏற்றுக்கொண்டு வெளியிடவும்',
    editDetails: 'விவரங்களைத் திருத்தவும்',
    publishedSuccess: 'வாழ்த்துக்கள்! உங்கள் கைவினைப் பொருள் சந்தையில் வெளியிடப்பட்டது.',
    material: 'பொருள் (Material)',
    category: 'வகை (Category)',
    dimensions: 'அளவு (Dimensions)',
    productionTime: 'தயாரிப்பு நேரம் (Time)',
    tags: 'குறிச்சொற்கள் (Tags)',
    heritageStory: 'கைவினைஞர் பாரம்பரியக் கதை',
    sentiment: 'உணர்வு மற்றும் தொனி',
    suggestedPrice: 'AI நியாயமான சந்தை விலை',
    bulkOrderAvailable: 'மொத்த கொள்முதல் கிடைக்கிறது',
    buyerInquiry: 'வாங்குபவர் ஆர்டர் கோரிக்கை',
    requestUnits: 'மொத்த ஆர்டர் கோரிக்கை அனுப்பவும்',
    quantity: 'அளவு (Units)',
    buyerName: 'உங்கள் பெயர் / நிறுவனம்',
    buyerContact: 'தொலைபேசி / மின்னஞ்சல்',
    offeredPrice: 'வழங்கப்படும் விலை (₹/அலகு)',
    sendRequest: 'கோரிக்கையை அனுப்பவும் (Send Request)',
    orderSubmitted: 'ஆர்டர் கோரிக்கை அனுப்பப்பட்டது!',
    pending: 'நிலுவையில் (Pending)',
    accepted: 'ஏற்றுக்கொள்ளப்பட்டது (Accepted)',
    listenToScreen: 'பக்கத்தைக் கேட்கவும்',
    viewEnhanced: 'AI ஸ்டுடியோ புகைப்படம்',
    viewOriginal: 'அசல் படம்',
    aiConfidence: 'AI துல்லியம்'
  },
  te: {
    appTitle: 'తంతు TANTU',
    tagline: 'చేతివృత్తుల కళాకారుల కోసం స్మార్ట్ కేటలాగింగ్ & మార్కెట్ వేదిక',
    artisanRole: 'కళాకారుడు (Artisan)',
    buyerRole: 'కొనుగోలుదారు (Buyer)',
    selectLanguage: 'మీ భాషను ఎంచుకోండి',
    selectLanguageSub: 'Select your preferred language to continue',
    continueBtn: 'కొనసాగించండి (Continue)',
    home: 'హోమ్',
    addProduct: 'ఉత్పత్తిని జోడించండి',
    myProducts: 'నా కళాఖండాలు',
    orders: 'ఆర్డర్ అభ్యర్థనలు',
    marketplace: 'కళాకారుల మార్కెట్',
    hello: 'నమస్కారం',
    welcomeBack: 'ఈరోజు మీరు ఏ కళాఖండాన్ని మార్కెట్లో ప్రదర్శించాలనుకుంటున్నారు?',
    addNewCraft: 'కొత్త స్మార్ట్ కేటలాగ్ సృష్టించండి',
    addNewCraftSub: 'ఫోటో తీసి మీ స్వంత గొంతుతో వివరించండి — AI స్వయంచాలకంగా వివరణ మరియు సరసమైన ధరను నిర్ణయిస్తుంది.',
    startNow: 'ప్రారంభించండి (Start)',
    totalProducts: 'మొత్తం కళాఖండాలు',
    activeOrders: 'క్రియాశీల ఆర్డర్లు',
    estEarnings: 'అంచనా ఆదాయం',
    recentUploads: 'ఇటీవల జోడించిన ఉత్పత్తులు',
    viewAll: 'అన్నీ చూడండి',
    step1Photo: '1. ఫోటో తీయండి లేదా ఎంచుకోండి',
    step1PhotoSub: 'ఉత్పత్తి యొక్క స్పష్టమైన ఫోటో తీయండి',
    step2Voice: '2. వాయిస్ ద్వారా చెప్పండి',
    step2VoiceSub: 'మైక్ నొక్కి 30 సెకన్లలో ఉత్పత్తి గురించి వివరించండి',
    step3Ai: '3. AI ప్రాసెసింగ్',
    step3AiSub: 'తంతు AI స్మార్ట్ కేటలాగ్‌ను సిద్ధం చేస్తోంది',
    step4Catalog: '4. స్మార్ట్ కేటలాగ్',
    step4CatalogSub: 'సిద్ధమైన కేటలాగ్‌ను సమీక్షించి ప్రచురించండి',
    takePhoto: 'కెమెరా తెరవండి',
    uploadPhoto: 'గ్యాలరీ నుండి ఎంచుకోండి',
    orUseSample: 'లేదా డెమో ఉత్పత్తిని ఎంచుకోండి:',
    tapToRecord: 'మాట్లాడటానికి మైక్ నొక్కండి',
    listening: 'వింటున్నాము... మాట్లాడండి',
    stopRecording: 'మాట్లాడటం పూర్తి చేయండి',
    playVoice: 'వాయిస్ వినండి',
    reRecord: 'మళ్లీ రికార్డ్ చేయండి',
    recordedSuccess: 'మీ వాయిస్ విజయవంతంగా రికార్డ్ చేయబడింది!',
    proceedToAi: 'AI కేటలాగ్ సిద్ధం చేయండి',
    approvePublish: 'ఆమోదించి మార్కెట్లో ప్రచురించండి',
    editDetails: 'వివరాలు సవరించండి',
    publishedSuccess: 'అభినందనలు! మీ కళాఖండం మార్కెట్లో విజయవంతంగా ప్రచురించబడింది.',
    material: 'పదార్థం (Material)',
    category: 'వర్గం (Category)',
    dimensions: 'కొలతలు (Dimensions)',
    productionTime: 'తయారీ సమయం (Time)',
    tags: 'ట్యాగ్‌లు (Tags)',
    heritageStory: 'కళాకారుడి కథ & వారసత్వం',
    sentiment: 'భావోద్వేగం మరియు శైలి',
    suggestedPrice: 'AI సూచించిన సరసమైన ధర',
    bulkOrderAvailable: 'టోకు కొనుగోలు అందుబాటులో ఉంది',
    buyerInquiry: 'కొనుగోలుదారు ఆర్డర్ అభ్యర్థన',
    requestUnits: 'టోకు ఆర్డర్ అభ్యర్థన పంపండి',
    quantity: 'పరిమాణం (Units)',
    buyerName: 'మీ పేరు / సంస్థ',
    buyerContact: 'ఫోన్ నంబర్ / ఇమెయిల్',
    offeredPrice: 'ప్రతిపాదిత ధర యూనిట్‌కు (₹)',
    sendRequest: 'అభ్యర్థన పంపండి (Send Request)',
    orderSubmitted: 'ఆర్డర్ అభ్యర్థన పంపబడింది!',
    pending: 'పెండింగ్‌లో ఉంది (Pending)',
    accepted: 'ఆమోదించబడింది (Accepted)',
    listenToScreen: 'ఈ పేజీని వినండి',
    viewEnhanced: 'AI స్టూడియో ఫోటో',
    viewOriginal: 'అసలు ఫోటో',
    aiConfidence: 'AI ఖచ్చితత్వం'
  }
};

export const getTranslation = (lang, key) => {
  const dictionary = TRANSLATIONS[lang] || TRANSLATIONS['en'];
  return dictionary[key] || TRANSLATIONS['en']?.[key] || key;
};
